apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    name: my-nginx
    rel: stable  
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        hostPort: 80
