apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-env
data:
  MONGODB_DBNAME: codeWithDan
  MONGODB_PASSWORD: password 
  MONGODB_ROLE: readWrite
  MONGODB_ROOT_PASSWORD: password 
  MONGODB_ROOT_ROLE: root 
  MONGODB_ROOT_USERNAME: dbadmin 
  MONGODB_USERNAME: webrole 

