apiVersion: v1
kind: Pod
metadata:
  name: my-busy-box
  labels:
    name: my-busy-box
    rel: stable  
spec:
  containers:
  - name: my-busy-box
    image: k8s.gcr.io/busybox

    args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 30;
        rm -rf /tmp/healthy; sleep 600

    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initialDelaySeconds: 5 
        periodSeconds: 5 

